function otrFuncion () { 
    serompe()
}


const serompe = () => { 
    return 3 + z
}


function seRompeAsincrona(){ 
 if(true) { 
    console.log('te quiero');
}
return serompe()
    
}


try {
otrFuncion()  
const serompeAsync = seRompeAsincrona()  
console.log(`el resultado de la suma es ${serompeAsync}`)
} catch (error) {
    console.error('vaya, algo se ha roto ')
    console.error(error.message)
    console.log('pero no pasa nada, lo hemos capturado')
}
